import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import './globals.css'
import { Toaster } from '@m-care/features/@shared/components/ui'

const roboto = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: {
    template: '%s | M - Care',
    default: 'M - Care'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} bg-grey-lite text-black`}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
