import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import './globals.css'

import { Toaster } from '@m-care/features/@shared/components/ui'

import { GlobalProviders } from '@m-care/features/@shared/context'

const roboto = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '900']
})

export const metadata: Metadata = {
  title: {
    template: '%s | M - Care',
    default: 'M - Care'
  },
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${roboto.className} bg-grey-lite text-black`}>
        <GlobalProviders>
          {children}
          <Toaster richColors={true} />
        </GlobalProviders>
      </body>
    </html>
  )
}
